name: CI

on:
  name: CI

  on:
    name: CI

    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
      workflow_dispatch: {}
      schedule:
        - cron: '0 2 * * *'

    jobs:
      tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.10'
          - name: Install deps
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install numpy pillow imageio pytest; fi
          - name: Run tests
            run: pytest -q

      synthetic_data:
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        needs: tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.10'
          - name: Install deps
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install numpy pillow imageio; fi
          - name: Generate synthetic data
            run: python3 scripts/generate_fake_phi_data.py
          - name: Validate generated data
            run: python3 scripts/ci_validate_synthetic.py
          - uses: actions/upload-artifact@v4
            with:
              name: synthetic-data
              path: synthetic_data
                  - name: Run tests
